In [182]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm

### Loading the data

In [43]:
data = pd.read_csv("Downloads/Motor vehicle insurance data.csv", delimiter = ';')
data.head()

/var/folders/yr/ygp7zpqx7js0hf1990jlzlbw0000gn/T/ipykernel_15242/2002396641.py:1: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv("Downloads/Motor vehicle insurance data.csv", delimiter = ';')

,ID,Date_start_contract,Date_last_renewal,Date_next_renewal,Date_birth,Date_driving_licence,Distribution_channel,Seniority,Policies_in_force,Max_policies,...,Area,Second_driver,Year_matriculation,Power,Cylinder_capacity,Value_vehicle,N_doors,Type_fuel,Length,Weight
0,1,05/11/2015,05/11/2015,05/11/2016,15/04/1956,20/03/1976,0,4,1,2,...,0,0,2004,80,599,7068.0,0,P,NaN,190
1,1,05/11/2015,05/11/2016,05/11/2017,15/04/1956,20/03/1976,0,4,1,2,...,0,0,2004,80,599,7068.0,0,P,NaN,190
2,1,05/11/2015,05/11/2017,05/11/2018,15/04/1956,20/03/1976,0,4,2,2,...,0,0,2004,80,599,7068.0,0,P,NaN,190
3,1,05/11/2015,05/11/2018,05/11/2019,15/04/1956,20/03/1976,0,4,2,2,...,0,0,2004,80,599,7068.0,0,P,NaN,190
4,2,26/09/2017,26/09/2017,26/09/2018,15/04/1956,20/03/1976,0,4,2,2,...,0,0,2004,80,599,7068.0,0,P,NaN,190

### Cleaning the data

In [51]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 105555 entries, 0 to 105554
Data columns (total 30 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   ID                    105555 non-null  int64
 1   Date_start_contract   105555 non-null  object
 2   Date_last_renewal     105555 non-null  object
 3   Date_next_renewal     105555 non-null  object
 4   Date_birth            105555 non-null  object
 5   Date_driving_licence  105555 non-null  object
 6   Distribution_channel  105555 non-null  object
 7   Seniority             105555 non-null  int64
 8   Policies_in_force     105555 non-null  int64
 9   Max_policies          105555 non-null  int64
 10  Max_products          105555 non-null  int64
 11  Lapse                 105555 non-null  int64
 12  Date_lapse            35147 non-null   object
 13  Payment               105555 non-null  int64
 14  Premium               105555 non-null  float64
 15  Cost_claims_year      105555 non-null  float64
 16  N_claims_year         105555 non-null  int64
 17  N_claims_history      105555 non-null  int64
 18  R_Claims_history      105555 non-null  float64
 19  Type_risk             105555 non-null  int64
 20  Area                  105555 non-null  int64
 21  Second_driver         105555 non-null  int64
 22  Year_matriculation    105555 non-null  int64
 23  Power                 105555 non-null  int64
 24  Cylinder_capacity     105555 non-null  int64
 25  Value_vehicle         105555 non-null  float64
 26  N_doors               105555 non-null  int64
 27  Type_fuel             103791 non-null  object
 28  Length                95226 non-null   float64
 29  Weight                105555 non-null  int64
dtypes: float64(5), int64(17), object(8)
memory usage: 24.2+ MB

In [53]:
data.describe()

,ID,Seniority,Policies_in_force,Max_policies,Max_products,Lapse,Payment,Premium,Cost_claims_year,N_claims_year,...,Type_risk,Area,Second_driver,Year_matriculation,Power,Cylinder_capacity,Value_vehicle,N_doors,Length,Weight
count,105555.000000,105555.000000,105555.000000,105555.000000,105555.000000,105555.000000,105555.000000,105555.000000,105555.000000,105555.000000,...,105555.000000,105555.000000,105555.000000,105555.000000,105555.000000,105555.000000,105555.000000,105555.000000,95226.000000,105555.000000
mean,26271.286789,6.696604,1.455649,1.837232,1.065842,0.221837,0.319180,315.892557,153.557305,0.394695,...,2.721804,0.273895,0.123708,2004.728038,92.682611,1617.759367,18413.657243,4.067898,4.252007,1191.262422
std,15388.309324,6.263911,0.928427,1.155536,0.267807,0.464858,0.466161,140.927969,1477.112362,1.105018,...,0.614835,0.445958,0.329250,6.767037,37.012645,604.697382,9135.074235,1.511839,0.393220,458.081834
min,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,40.140000,0.000000,0.000000,...,1.000000,0.000000,0.000000,1950.000000,0.000000,49.000000,270.460000,0.000000,1.978000,43.000000
25%,12925.000000,3.000000,1.000000,1.000000,1.000000,0.000000,0.000000,241.610000,0.000000,0.000000,...,3.000000,0.000000,0.000000,2001.000000,75.000000,1390.000000,13127.210000,3.000000,3.999000,1043.000000
50%,26082.000000,4.000000,1.000000,2.000000,1.000000,0.000000,0.000000,292.280000,0.000000,0.000000,...,3.000000,0.000000,0.000000,2005.000000,90.000000,1598.000000,17608.770000,5.000000,4.230000,1205.000000
75%,39754.000000,9.000000,2.000000,2.000000,1.000000,0.000000,1.000000,361.640000,0.000000,0.000000,...,3.000000,1.000000,0.000000,2008.000000,110.000000,1910.000000,22595.000000,5.000000,4.443000,1388.000000
max,53502.000000,40.000000,17.000000,17.000000,4.000000,7.000000,1.000000,2993.340000,260853.240000,25.000000,...,4.000000,1.000000,1.000000,2018.000000,580.000000,7480.000000,220675.800000,6.000000,8.218000,7300.000000

In [45]:
data.columns

Index(['ID', 'Date_start_contract', 'Date_last_renewal', 'Date_next_renewal',
       'Date_birth', 'Date_driving_licence', 'Distribution_channel',
       'Seniority', 'Policies_in_force', 'Max_policies', 'Max_products',
       'Lapse', 'Date_lapse', 'Payment', 'Premium', 'Cost_claims_year',
       'N_claims_year', 'N_claims_history', 'R_Claims_history', 'Type_risk',
       'Area', 'Second_driver', 'Year_matriculation', 'Power',
       'Cylinder_capacity', 'Value_vehicle', 'N_doors', 'Type_fuel', 'Length',
       'Weight'],
      dtype='object')

In [47]:
data.isnull().sum()

ID                          0
Date_start_contract         0
Date_last_renewal           0
Date_next_renewal           0
Date_birth                  0
Date_driving_licence        0
Distribution_channel        0
Seniority                   0
Policies_in_force           0
Max_policies                0
Max_products                0
Lapse                       0
Date_lapse              70408
Payment                     0
Premium                     0
Cost_claims_year            0
N_claims_year               0
N_claims_history            0
R_Claims_history            0
Type_risk                   0
Area                        0
Second_driver               0
Year_matriculation          0
Power                       0
Cylinder_capacity           0
Value_vehicle               0
N_doors                     0
Type_fuel                1764
Length                  10329
Weight                      0
dtype: int64

In [91]:
data['Date_lapse'].sample(5)

56993           NaN
93595    28/01/2016
96368           NaN
93280           NaN
70328           NaN
Name: Date_lapse, dtype: object

In [95]:
data['Policy_active'] = data['Date_lapse'].isnull().astype(int) # Assumed that null values meant that the policy is active

In [105]:
data['Policy_active'].sample(10)

47648     0
30219     0
29358     1
17971     0
42069     1
68706     0
100014    0
46909     0
78278     1
9155      1
Name: Policy_active, dtype: int64

In [118]:
# Customer age
data['Customer_age'] = pd.to_datetime('today').year - pd.to_datetime(data['Date_birth'], dayfirst=True).dt.year

In [114]:
# Car age
data['Car_age'] = pd.to_datetime('today').year - data['Year_matriculation']

In [126]:
data[['Customer_age','Car_age']].sample(10)

        Customer_age  Car_age
88733             68       22
37170             69        8
18831             36       15
22928             61       25
103168            50       23
81254             62       26
29148             50       15
98800             51       19
8889              58       16
76483             38       14

In [128]:
data.head()

,ID,Date_start_contract,Date_last_renewal,Date_next_renewal,Date_birth,Date_driving_licence,Distribution_channel,Seniority,Policies_in_force,Max_policies,...,Cylinder_capacity,Value_vehicle,N_doors,Type_fuel,Length,Weight,Poloicy_active,Policy_active,Customer_age,Car_age
0,1,05/11/2015,05/11/2015,05/11/2016,15/04/1956,20/03/1976,0,4,1,2,...,599,7068.0,0,P,NaN,190,1,1,69,21
1,1,05/11/2015,05/11/2016,05/11/2017,15/04/1956,20/03/1976,0,4,1,2,...,599,7068.0,0,P,NaN,190,1,1,69,21
2,1,05/11/2015,05/11/2017,05/11/2018,15/04/1956,20/03/1976,0,4,2,2,...,599,7068.0,0,P,NaN,190,1,1,69,21
3,1,05/11/2015,05/11/2018,05/11/2019,15/04/1956,20/03/1976,0,4,2,2,...,599,7068.0,0,P,NaN,190,1,1,69,21
4,2,26/09/2017,26/09/2017,26/09/2018,15/04/1956,20/03/1976,0,4,2,2,...,599,7068.0,0,P,NaN,190,1,1,69,21

In [136]:
data.drop(columns = ["Poloicy_active"], inplace = True)

,ID,Date_start_contract,Date_last_renewal,Date_next_renewal,Date_birth,Date_driving_licence,Distribution_channel,Seniority,Policies_in_force,Max_policies,...,Power,Cylinder_capacity,Value_vehicle,N_doors,Type_fuel,Length,Weight,Policy_active,Customer_age,Car_age
0,1,05/11/2015,05/11/2015,05/11/2016,15/04/1956,20/03/1976,0,4,1,2,...,80,599,7068.00,0,P,NaN,190,1,69,21
1,1,05/11/2015,05/11/2016,05/11/2017,15/04/1956,20/03/1976,0,4,1,2,...,80,599,7068.00,0,P,NaN,190,1,69,21
2,1,05/11/2015,05/11/2017,05/11/2018,15/04/1956,20/03/1976,0,4,2,2,...,80,599,7068.00,0,P,NaN,190,1,69,21
3,1,05/11/2015,05/11/2018,05/11/2019,15/04/1956,20/03/1976,0,4,2,2,...,80,599,7068.00,0,P,NaN,190,1,69,21
4,2,26/09/2017,26/09/2017,26/09/2018,15/04/1956,20/03/1976,0,4,2,2,...,80,599,7068.00,0,P,NaN,190,1,69,21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105550,53498,30/07/2018,30/07/2018,30/07/2019,25/07/1981,14/02/2007,0,1,1,1,...,110,1997,24320.00,5,D,4.740,1480,1,44,25
105551,53499,16/08/2018,16/08/2018,16/08/2019,08/12/1976,29/11/2017,0,1,1,1,...,129,1998,30861.97,5,P,4.650,1440,1,49,12
105552,53500,21/11/2018,21/11/2018,21/11/2019,01/04/1974,05/10/2011,0,1,1,1,...,55,999,7800.00,5,P,3.495,830,1,51,26
105553,53501,21/11/2018,21/11/2018,21/11/2019,15/09/1946,02/02/1982,0,1,1,1,...,90,1753,16610.00,5,D,4.555,1399,1,79,21
105554,53502,01/10/2018,01/10/2018,01/10/2019,09/05/1973,30/09/1991,1,1,1,1,...,140,1968,33400.00,5,D,4.854,1699,1,52,15

In [148]:
data['Type_fuel'].value_counts(dropna=False)

Type_fuel
D      64998
P      38793
NaN     1764
Name: count, dtype: int64

In [144]:
data["Type_fuel"].sample(5) # could transfrom this column into a binary column.

31228    D
2713     P
39435    D
35162    P
80547    D
Name: Type_fuel, dtype: object

In [160]:
data['Type_fuel'].fillna(data['Type_fuel'].mode()[0], inplace=True) # filled the mode/ most common fuel type to replace the missing values

In [162]:
data['Type_fuel'].value_counts(dropna=False)

Type_fuel
D    66762
P    38793
Name: count, dtype: int64

In [164]:
data['Date_lapse'].fillna('Active') #This would indicate whether policy is active or ended.

0         Active
1         Active
2         Active
3         Active
4         Active
           ...
105550    Active
105551    Active
105552    Active
105553    Active
105554    Active
Name: Date_lapse, Length: 105555, dtype: object

In [156]:
data['Length'].describe()

count    95226.000000
mean         4.252007
std          0.393220
min          1.978000
25%          3.999000
50%          4.230000
75%          4.443000
max          8.218000
Name: Length, dtype: float64

In [166]:
data['Length'].fillna(data['Length'].median()) 
#Filled in the median length of cars. This will not affect outliers.

0         4.230
1         4.230
2         4.230
3         4.230
4         4.230
          ...
105550    4.740
105551    4.650
105552    3.495
105553    4.555
105554    4.854
Name: Length, Length: 105555, dtype: float64

In [176]:
data.head()

,ID,Date_start_contract,Date_last_renewal,Date_next_renewal,Date_birth,Date_driving_licence,Distribution_channel,Seniority,Policies_in_force,Max_policies,...,Cylinder_capacity,Value_vehicle,N_doors,Type_fuel,Length,Weight,Poloicy_active,Policy_active,Customer_age,Car_age
0,1,05/11/2015,05/11/2015,05/11/2016,15/04/1956,20/03/1976,0,4,1,2,...,599,7068.0,0,P,4.23,190,1,1,69,21
1,1,05/11/2015,05/11/2016,05/11/2017,15/04/1956,20/03/1976,0,4,1,2,...,599,7068.0,0,P,4.23,190,1,1,69,21
2,1,05/11/2015,05/11/2017,05/11/2018,15/04/1956,20/03/1976,0,4,2,2,...,599,7068.0,0,P,4.23,190,1,1,69,21
3,1,05/11/2015,05/11/2018,05/11/2019,15/04/1956,20/03/1976,0,4,2,2,...,599,7068.0,0,P,4.23,190,1,1,69,21
4,2,26/09/2017,26/09/2017,26/09/2018,15/04/1956,20/03/1976,0,4,2,2,...,599,7068.0,0,P,4.23,190,1,1,69,21

In [178]:
data.isnull().sum()

ID                      0
Date_start_contract     0
Date_last_renewal       0
Date_next_renewal       0
Date_birth              0
Date_driving_licence    0
Distribution_channel    0
Seniority               0
Policies_in_force       0
Max_policies            0
Max_products            0
Lapse                   0
Date_lapse              0
Payment                 0
Premium                 0
Cost_claims_year        0
N_claims_year           0
N_claims_history        0
R_Claims_history        0
Type_risk               0
Area                    0
Second_driver           0
Year_matriculation      0
Power                   0
Cylinder_capacity       0
Value_vehicle           0
N_doors                 0
Type_fuel               0
Length                  0
Weight                  0
Poloicy_active          0
Policy_active           0
Customer_age            0
Car_age                 0
dtype: int64

In [184]:
data.drop(columns = ["Poloicy_active"], inplace = True)

In [186]:
data.isnull().sum()

ID                      0
Date_start_contract     0
Date_last_renewal       0
Date_next_renewal       0
Date_birth              0
Date_driving_licence    0
Distribution_channel    0
Seniority               0
Policies_in_force       0
Max_policies            0
Max_products            0
Lapse                   0
Date_lapse              0
Payment                 0
Premium                 0
Cost_claims_year        0
N_claims_year           0
N_claims_history        0
R_Claims_history        0
Type_risk               0
Area                    0
Second_driver           0
Year_matriculation      0
Power                   0
Cylinder_capacity       0
Value_vehicle           0
N_doors                 0
Type_fuel               0
Length                  0
Weight                  0
Policy_active           0
Customer_age            0
Car_age                 0
dtype: int64